### ISSUE TITLE
When restarting Kano an error occured while updating the catalog

### ISSUE THREAD

**Issue by cnouguier** [kalisio/kano#112]
kargo-kano_kano.1.yifilpd9opc8@dev-worker-1    | error: Unhandled Rejection: E11000 duplicate key error collection: kano.catalog index: name_1 dup key: { : "Layers.S2" } {"type":"FeathersError","name":"GeneralError","code":500,"className":"general-error","data":{"code":11000},"errors":{},"stack":"GeneralError: E11000 duplicate key error collection: kano.catalog index: name_1 dup key: { : \"Layers.S2\" }\n    at new GeneralError (/opt/kalisio/kdk/node_modules/feathers-errors/lib/index.js:177:17)\n    at errorHandler (/opt/kalisio/kdk/node_modules/feathers-mongodb/lib/error-handler.js:22:21)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}

**Comment by cnouguier** [comment]
Seems to be fixed now
